name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=$(echo "ghcr.io/${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          TAG=${GITHUB_REF##*/}
          docker build -t "$IMAGE_NAME:latest" -t "$IMAGE_NAME:$TAG" .
          docker push "$IMAGE_NAME:latest"
          docker push "$IMAGE_NAME:$TAG"

      - name: Create GitHub Release and Changelog
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Gotify notification
        run: |
          curl -X POST "https://gotify.tylerripley.com/message?token=AE_roYUhK4A2pXy" \
            -H "Content-Type: application/json" \
            -d '{
              "title": "New Release Deployed",
              "message": "Docker image for tag ${{ github.ref_name }} has been built and pushed to ghcr.io.",
              "priority": 5
            }'
